"""Private deterministic Markdown generators used by tools.scan_ids (no network or runtime changes)."""
import html
from pathlib import Path
from typing import TYPE_CHECKING, Dict, Optional

from idnumbers import FailureReason, format_id, normalize_id
from idnumbers.registry import list_supported_countries
if TYPE_CHECKING:
    from tests.helpers.failure_reasons import ReasonVector

MARKER = '<!-- Generated by python -m tools.scan_ids; do not edit. -->'


def cell(value: object) -> str:
    """Preserve literal data while escaping HTML and Markdown table delimiters."""
    return '<code>' + html.escape(str(value)).replace('|', '&#124;').replace('`', '&#96;').replace('\n', '&#10;') + '</code>'


def country_pages() -> Dict[str, str]:
    pages = {}
    index = [MARKER, '# Countries', '',
             'Generated from current METADATA, not a complete legal specification. Examples are synthetic,',
             'not personal data or proof of issuance. Each snippet runs independently.', '',
             '[Input formats](../INPUT_FORMATS.md) · [Failure reasons](../FAILURE_REASONS.md)', '',
             '| Country | Alpha-2 | Primary class | ID classes |', '| --- | --- | --- | --- |']
    for entry in sorted(list_supported_countries(), key=lambda entry: entry.alpha3):
        classes = sorted(entry.id_types, key=lambda cls: (cls.__module__, cls.__name__))
        primary = entry.national_id
        index.append(f'| [{entry.name} ({entry.alpha3})]({entry.alpha3}.md) | {entry.alpha2} | '
                     f'{primary.__name__} | {len(classes)} |')
        lines = [MARKER, f'# {entry.name} ({entry.alpha3} / {entry.alpha2})', '',
                 '[Country index](README.md) · [Metadata definitions](../nationalid/METADATA.md)', '',
                 f'Primary class: `{primary.__module__}.{primary.__name__}`.', '',
                 'Current implementation metadata, not a promise that an ID was issued. All examples are synthetic.']
        for cls in classes:
            module = cls.__module__
            lines.extend(['', f'## {cls.__name__}', '',
                          f'[Source](../../{module.replace(".", "/")}.py) · '
                          f'[API](https://identique.github.io/idnumbers/{module}.{cls.__name__}.html)', '',
                          '| METADATA field | Value |', '| --- | --- |'])
            for key, value in sorted(vars(cls.METADATA).items()):
                if key == 'regexp':
                    value = value.pattern
                lines.append(f'| {key} | {cell(value)} |')
            lines.extend(['', 'Reference links recorded by this implementation (source quality varies):', ''])
            lines.extend(f'- <{link}>' for link in cls.METADATA.links)
            lines.extend(['', '```python', f'from {module} import {cls.__name__}', '',
                          f'number = {cls.METADATA.example!r}', f'assert {cls.__name__}.validate(number)'])
            if cls.METADATA.parsable:
                lines.extend([f'info = {cls.__name__}.parse(number)', 'assert info is not None'])
            lines.append('```')
        pages[f'{entry.alpha3}.md'] = '\n'.join(lines) + '\n'
    pages['README.md'] = '\n'.join(index) + '\n'
    return pages


def witness(vector: Optional['ReasonVector']) -> str:
    if vector is None:
        return '—'
    reason = 'valid' if vector.expected is None else vector.expected.value
    return cell(vector.id_number) + ' → ' + cell(reason)


def failure_guide() -> str:
    from tests.helpers.failure_reasons import iter_reason_matrix

    lines = [MARKER, '# Failure reasons', '',
             'The unified `validate()` and `parse_id_info()` select the primary ID only. Use',
             '`failure_reason(id_class, number)` for secondary types. A valid ID returns no failure reason.',
             'Diagnostics are best effort and never change validity or normalize validation input.', '',
             'Precedence: unsupported country, length, format, definite checksum mismatch, traced calendar',
             'failure, then generic `validation_failed`. Diagnostic candidate cleanup is not input acceptance.',
             'Computed checksums without a named `checksum` regexp group can be inconclusive.',
             'Validator/parser exceptions also use the generic fallback. `not_parsable` is only produced by',
             '`parse_id_info()` for a valid ID with no parser or no extracted information.',
             'This enum is non-exhaustive: handle unknown future reasons with a generic fallback.', '',
             '| Enum | Code |', '| --- | --- |']
    lines.extend(f'| {reason.name} | {cell(reason.value)} |' for reason in FailureReason)
    lines.extend(['', '```python', 'from idnumbers import FailureReason, failure_reason, parse_id_info, validate',
                  'from idnumbers.nationalid import AUS', '',
                  "assert validate('TW', 'A12345').reason == FailureReason.INVALID_LENGTH",
                  "assert validate('TW', 'A123456788').reason == FailureReason.CHECKSUM_MISMATCH",
                  "assert validate('ZA', '7602300675085').reason == FailureReason.INVALID_BIRTHDATE",
                  "assert failure_reason(AUS.MedicareNumber, '2123 45670 1') is None",
                  "parsed = parse_id_info('US', '012-12-0928')",
                  'assert not parsed.ok and parsed.reason == FailureReason.NOT_PARSABLE', '```', '',
                  '## Frozen per-class witnesses', '',
                  'Source: [frozen vectors](../tests/helpers/failure_reason_vectors.json), not inferred from diagnostic output.',
                  'All 104 registered non-alias classes: 628 vectors, 74 flipped-checksum witnesses',
                  '(60 specific, 14 generic), and 34 checksum-repaired impossible dates across 31 countries.',
                  'These are finite observations, not exhaustive coverage of every input or checksum class.',
                  'Deferred refinements: [#506 (v1.16.0)](https://github.com/identique/idnumbers/issues/506).', '',
                  '| Class | Valid | Invalid lengths | Invalid format | Checksum witness / note | Date witness / note |',
                  '| --- | --- | --- | --- | --- | --- |'])
    for row in sorted(iter_reason_matrix(), key=lambda row: row.key):
        lines.append(f'| [{row.key}](countries/{row.country}.md) | {witness(row.valid)} | '
                     + '<br>'.join(witness(vector) for vector in row.length)
                     + f' | {witness(row.format)} | {witness(row.checksum)}<br>{cell(row.checksum_note)} | '
                     + f'{witness(row.birthdate)}<br>{cell(row.birthdate_note)} |')
    return '\n'.join(lines) + '\n'


def input_guide() -> str:
    lines = [MARKER, '# Input formats', '',
             'Unified validation and parsing do **not** pre-normalize: they pass the original input to the primary',
             'country class. Classes differ in separator and lowercase handling; metadata regexps alone may not',
             'describe preprocessing. Validation is whole-input with ASCII digits; surrounding whitespace is',
             'rejected except where a class explicitly permits it (Irish PPS permits one trailing space).',
             'Non-string IDs are not coerced. Class `parse()` returns `None` for malformed inputs where available.', '',
             '`normalize_id()` and `format_id()` are optional, primary-only UI helpers, **not validation**.',
             'Normalization uppercases, removes whitespace (including zero-width controls) and `. - / ( )`',
             'when masks indicate separators. Without separator masks, allowed-length punctuation can remain:',
             "Finland's century signs are significant. `+` is never removed. Formatting is length-only;", 
             'it can produce invalid characters/checksums. Normalization does not reject unknown lengths.',
             'Always validate the chosen representation separately.',
             'Sweden preserves a significant plus before the last four digits in both 10- and 12-digit forms.',
             'Its preferred mask pattern has minus, so a valid plus-formatted ID can fail that UI pattern.',
             "Greece's validator accepts Greek letters but the ASCII `L` UI token does not; no transliteration occurs.",
             'Input patterns describe literal mask layouts, not the complete validator language.', '',
             '```python', 'from idnumbers import format_id, get_input_mask, normalize_id, validate', '',
             "assert normalize_id('FI', '131052-308T') == '131052-308T'",
             "for number in ('811218+9876', '19811218+9876'):",
             "    assert format_id('SE', number) == number",
             "    assert validate('SE', number).is_valid",
             "mask = get_input_mask('SE')", 'assert mask is not None',
             "assert mask.pattern.fullmatch('811218+9876') is None", '```', '',
             '## Primary-example observations', '',
             'Empirical only: one synthetic current METADATA example per country, plus its lowercase, surrounding',
             'space, normalized and formatted variants. This is **not** a complete country input policy.',
             'CHE, CHL, KOR and USA reject their normalized example; all 78 formatted examples validate.', '',
             '| Country | Example | Lowercase | Surrounding spaces | Normalized | Formatted |',
             '| --- | --- | --- | --- | --- | --- |']
    for entry in sorted(list_supported_countries(), key=lambda entry: entry.alpha3):
        cls = entry.national_id
        value = cls.METADATA.example
        variants = [value.lower(), ' ' + value + ' ', normalize_id(entry.alpha3, value), format_id(entry.alpha3, value)]
        outcomes = ['yes' if cls.validate(variant) else 'no' for variant in variants]
        lines.append(f'| [{entry.alpha3}](countries/{entry.alpha3}.md) | {cell(value)} | ' + ' | '.join(outcomes) + ' |')
    return '\n'.join(lines) + '\n'


def write_files(files: Dict[Path, str], check: bool = False, managed_dir: Optional[Path] = None) -> None:
    """Check missing/drifting/stale managed pages without deleting any user files."""
    failures = []
    if managed_dir is not None and managed_dir.exists():
        for path in managed_dir.glob('*.md'):
            if path not in files and path.read_text(encoding='utf-8').startswith(MARKER):
                failures.append(f'stale managed page: {path}')
    if failures:
        raise ValueError('\n'.join(failures))
    for path, source in files.items():
        if check:
            if not path.exists() or path.read_text(encoding='utf-8') != source:
                failures.append(f'missing or changed generated page: {path}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(source, encoding='utf-8')
    if failures:
        raise ValueError('\n'.join(failures))


def generate(markdown_dir: Optional[Path], failure_file: Optional[Path], input_file: Optional[Path], check: bool) -> None:
    files = {} if markdown_dir is None else {markdown_dir / name: source for name, source in country_pages().items()}
    if failure_file is not None:
        files[failure_file] = failure_guide()
    if input_file is not None:
        files[input_file] = input_guide()
    write_files(files, check, markdown_dir)
