name: Bump Release Version with PR
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version value'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    name: Bump setup.py version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update version
        run: |
          echo "==== before update ========================="
          cat VERSION
          echo "${{ inputs.version }}" > VERSION
          sed -i -e "1i <option {{ 'selected' if env['version'] == '${{ inputs.version }}' else '' }} value=\"${{ inputs.version }}\">${{ inputs.version }}</option>" \
              docs/pdoc_template/version.html.jinja2
          echo "==== after update ========================="
          cat VERSION
          git add VERSION
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Bump version to ${{ inputs.version }}
          committer: Microdata Bot <microdataxyz@outlook.com>
          title: Bump version to ${{ inputs.version }}
          body: Bump version by ${{ github.actor }}

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
