name: apidoc

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version value'
  workflow_call:
    inputs:
      version:
        description: 'Version value'
        type: string

# security: restrict permissions for CI jobs.
permissions:
  contents: write
  pages: write

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install pdoc
      - name: build dev build
        if: inputs.version == ''
        run: pdoc --template-directory ./docs/pdoc_template -o pdocs --footer-text "idnumbers $(cat ./VERSION)+, dev version included" idnumbers
      - name: build prod build
        if: inputs.version != ''
        run: pdoc --template-directory ./docs/pdoc_template -o pdocs --footer-text "idnumbers ${{ inputs.version }}" idnumbers
      - uses: actions/upload-artifact@v3
        with:
          name: apidoc
          path: pdocs
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v3
        with:
          name: apidoc
          path: pdocs
      - run: git config --local user.email "microdataxyz@outlook.com"
      - run: git config --local user.name "Microdata Bot"
      - name: deploy dev apidoc
        if: inputs.version == ''
        run: |
          ls pdocs
          cp -rf pdocs/* ./docs
          git add ./docs
          git diff-index --quiet HEAD || git commit -m "Update dev doc"
      - name: deploy prod apidoc
        if: inputs.version != ''
        run: |
          ls pdocs
          cp -rf pdocs ./docs/v${{ inputs.version }}
          git add ./docs
          git diff-index --quiet HEAD || git commit -m "Add release doc v${{ inputs.version }}"
      - run: git push origin gh-pages
