name: pypi test cronjob (download idnumbers from pypi)

on:
  schedule:
    - cron: '5 1 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install idnumbers
      - name: Test with python pypi_spec
        run: |
          python -m tests.pypi_spec
